### ISSUE TITLE
Smaller Icon size distortion

### ISSUE THREAD

**Issue by wjramos** [choffmeister/adobe-illustrator-icnsexport#7] opened 2015-06-05 15:11 UTC
Please refer to tinalatif/flat.icns#151, 

I can confirm that icons appear 'glitched' in several sizes:
- Launchpad folder view
- Finder list view
- App 'Get Info' small icon (top left)
- Spotlight Search (other options)

I am not sure what the exact causes of this could be, other than possibly missing icon sizes in the icns file

**Comment by choffmeister** [comment] 2015-06-14 09:12
Yes I can confirm this error. Not really sure what the problem is there. Have to wait until tomorrow when I have access to Illustrator again to investigate what is going wrong here.

On your assumption regarding missing image sizes: I don't thinks this is the problem. If https://en.wikipedia.org/wiki/Apple_Icon_Image_format is correct and complete, than the script exports all modern image sizes, that are `icp4` to `ic15` (which are the ones supported since OS X 10.7).

I remember that I experienced this kind of disported export from the Illustrator function `doc.exportFile` directly and hence guess, that it is a problem with the actual PNG exporting itself. But will look into it tomorrow. Can you paste a link of a `.ai` file here, thats export is distorted?

**Comment by choffmeister** [comment] 2015-06-15 06:48
Have downloaded https://github.com/tinalatif/flat.icns/blob/master/icns/unarchiver.icns and exported it with the current version of the script (using Adobe Illustratror CS6): This is the result is this https://choffmeister.de/unarchiver.icns.

Opening this `.icns` file with preview I see eleven perfectly valid images in different sizes. How ever, running

```
iconutil -c iconset unarchiver.icns
```

yields https://choffmeister.de/unarchiver.iconset.zip which contains a distorted `icon_16x16.png` and `icon_32x32.png` which is strange, since the `icon_16x16@2x.png` is ok (and has the same size as the distorted non-retina 32x32 version).

Anyone any more ideas?

**Comment by choffmeister** [comment] 2015-06-15 07:03
I changed the script to export all the images as one `.icns` as well as individual `.png` files. These files are correct and have the correct sizes.

**Comment by choffmeister** [comment] 2015-06-15 07:14
@wjramos Found a quick fix for the problem (see PR #8). Can you please check, if this fixes the issue for you?

**Comment by wjramos** [comment] 2015-07-02 17:39
Taking a look now - sorry for the delay

**Comment by wjramos** [comment] 2015-07-02 20:21
Using the updated script : 
![screenshot 2015-07-02 13 20 52](https://cloud.githubusercontent.com/assets/5625810/8486929/4311244a-20bd-11e5-98aa-1ee05c18811b.png)

Looking good,

However:

Running iconutil -c iconset on the new icon I receive the same results: 

![screenshot 2015-07-02 13 26 36](https://cloud.githubusercontent.com/assets/5625810/8487026/fca623ba-20bd-11e5-96d1-ba515119447a.png)

**Comment by choffmeister** [comment] 2015-07-02 20:27
Great. Merged the fix. If problem occurs again feel free to reopen this issue.

**Comment by choffmeister** [comment] 2015-07-02 20:28
Ahh. Slow mobile connection made me overlook the last sentence... :(

**Comment by wjramos** [comment] 2015-07-02 20:35
I'm not sure if this could be related - when I open any default app .icns in Preview there appears to be one image at each size, but with icons exported with this script there appears to be duplicate 32, 64, 256, and 512 resolutions

Update: Actually, that's not universally true - some other applications I inspected the icons of do indeed have duplicate sizes when viewed within Preview

**Closed** 2019-07-03 16:31 UTC
